version: "3.8"
service:
  browser:
    image: nginx
    ports: 
      - "8080:80"
    restart: always

  mysql:
    image: mysqlimage
    enviroment:
      MYSQL_ROOT_PASSWORD: "jkefjkwefwlejkf"
      MYSQL_DATABASE: 'fjekjfek'
    restart: always
    volume:
      - mysql/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin image
    enviroment:

    ports: 
      - "8081:80"
    restart: always
    depends_on:
      - mysql
