export const REASONS = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  BEARER_NOT_FOUND: "BEARER_NOT_FOUND",
  INVALID_2FA_CODE: "INVALID_2FA_CODE",
  ROLE_DENIED: "ROLE_DENIED",
  BAD_REQUEST: "BAD_REQUEST",
} as const;

export type Reason = typeof REASONS[keyof typeof REASONS];


export const ACTIONS = {
  LOGIN_ATTEMPT: "LOGIN_ATTEMPT",
  LOGOUT: "LOGOUT",
  AUTH_ATTEMPT: "AUTH_ATTEMPT",
  DELETE_USER: "DELETE_USER",
  CREATE_BLOG: "CREATE_BLOG",
  UPDATE_BLOG: "UPDATE_BLOG",
} as const;

export type Action = typeof ACTIONS[keyof typeof ACTIONS];
